name       : gnome-bluetooth
version    : '42.2'
release    : 29
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/42/gnome-bluetooth-42.2.tar.xz : 8ce8ecfab28272db1830a63f08f9ccb5304734d1be2dbfce795fe4029e629f0c
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk4)
    - pkgconfig(upower-glib)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
    - gnome-bluetooth-1-common
setup      : |
    %meson_configure -Dgtk_doc=true -Dsendto=false
build      : |
    %ninja_build
install    : |
    %ninja_install
