name       : gnome-bluetooth
version    : 3.34.0
release    : 21
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.34/gnome-bluetooth-3.34.0.tar.xz : e867e67423e1dc78c56c2ea11dec066ce0254238d559e4777c80fa2935eb6baf
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
