name       : gnome-bluetooth
version    : 3.28.2
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.28/gnome-bluetooth-3.28.2.tar.xz : 1f4961ac33b5f9ce5e6e01ea2c08ad29cc98ed2b8878e38da867235b28a50732
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
