name       : gnome-bluetooth
version    : 3.20.1
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.20/gnome-bluetooth-3.20.1.tar.xz : ea9050b5f3b94ef279febae4cb789c2500a25344c784f650fe7f932fcd6798fe
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
