name       : gnome-bluetooth
version    : 3.28.1
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.28/gnome-bluetooth-3.28.1.tar.xz : 5633a99b50770de398ebdc580c8f502c7315d9634638db73611b8b740ace7ebc
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
