name       : gnome-bluetooth
version    : 3.34.1
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.34/gnome-bluetooth-3.34.1.tar.xz : 3ec91076c2822cd1f9abdc8e27663c3bda4c9c8a7a9773f9e92bfbf2b745d386
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
