name       : gnome-bluetooth
version    : 3.32.1
release    : 20
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.32/gnome-bluetooth-3.32.1.tar.xz : 6441cafd313af94fba28b701698074f97d693b9023788a74e8e6f16f817ba1aa
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
