name       : gnome-bluetooth
version    : 3.16.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.16/gnome-bluetooth-3.16.1.tar.xz : 3feb202d6780a53bc4a570eab5b0179f9351b32c1d3f28151ac2d222453ae08b
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - bluez
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/icons/hicolor/icon-theme.cache
