name       : gnome-bluetooth
version    : 3.34.3
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/3.34/gnome-bluetooth-3.34.3.tar.xz : 0a068e3bddbbdab46991521e6624098579abe80da242398bdd579c4ca6926422
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
setup      : |
    %meson_configure -Dgtk_doc=true -Dicon_update=false
build      : |
    %meson_build
install    : |
    %meson_install
