name       : gnome-bluetooth
version    : 3.18.2
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.18/gnome-bluetooth-3.18.2.tar.xz : d8df073c331df0f97261869fb77ffcdbf4e3e4eaf460d3c3ed2b16e03d9c5398
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - bluez
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
