name       : gnome-bluetooth
version    : '42.5'
release    : 32
source     :
    - https://download.gnome.org/sources/gnome-bluetooth/42/gnome-bluetooth-42.5.tar.xz : a4f5f1ac2dbb7b7b92f7d6d2b42c030f62aed9b5426b9dc116946041f3cba8f7
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - pkgconfig(bluez)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gsound)
    - pkgconfig(gtk4)
    - pkgconfig(upower-glib)
    - gtk-doc
    - itstool
rundeps    :
    - bluez
    - gnome-bluetooth-1-common
setup      : |
    %meson_configure -Dgtk_doc=true -Dsendto=false
build      : |
    %ninja_build
install    : |
    %ninja_install
