name       : gnome-bluetooth
version    : 3.18.0
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.18/gnome-bluetooth-3.18.0.tar.xz : f5c0d43226c4ec6a545dddb86181adadbc2b5cf720b640026003b9660fba0b8f
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
builddeps  :
    - bluez
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
