name       : gnome-bluetooth
version    : 3.20.0
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-bluetooth/3.20/gnome-bluetooth-3.20.0.tar.xz : 93b3ca16b348a168d044b3f777049b7dba2a9292c4adb2751a771e3bc5e4eb53
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : The GNOME Bluetooth Subsystem
description: |
    The GNOME Bluetooth Subsystem
component  : desktop.gnome
builddeps  :
    - bluez
    - pkgconfig(libnotify)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
